wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.2
LEARNING_RATE:
  value: 0.1
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
