wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.3
LEARNING_RATE:
  value: 0.1
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
