wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.38770551949311094
LEARNING_RATE:
  value: 0.060682114043510496
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
