wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.3929149161219848
LEARNING_RATE:
  value: 0.0744096270041523
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
