wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.3665162363040123
LEARNING_RATE:
  value: 0.05348797213279188
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
