wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.984450524298528
LEARNING_RATE:
  value: 0.06370048414430755
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
