wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.211768047155532
LEARNING_RATE:
  value: 0.05282544568095147
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
