wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.8299980348421863
LEARNING_RATE:
  value: 0.0984568726079623
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
