wandb_version: 1

BATCH_SIZE:
  value: 256
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.4757638299429752
LEARNING_RATE:
  value: 0.03029823556577694
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
