wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.7922831097090091
LEARNING_RATE:
  value: 0.06401796085070496
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
