wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.3051986894363009
LEARNING_RATE:
  value: 0.03463954216962929
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
