wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.10751087961653567
LEARNING_RATE:
  value: 0.017743060138261827
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
