wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.31421676679918953
LEARNING_RATE:
  value: 0.06793032303303961
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
