wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.10900266427233656
LEARNING_RATE:
  value: 0.06116206469694817
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
