wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.31353589539240045
LEARNING_RATE:
  value: 0.04183662295172285
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
