wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.2278641204251994
LEARNING_RATE:
  value: 0.06422652014630456
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: sgd
