wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.208064989440864
LEARNING_RATE:
  value: 0.02386562266312346
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
