wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.7756438071954204
LEARNING_RATE:
  value: 0.3328213169367854
NUMBER_HIDDEN_LAYERS:
  value: 2
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
