wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.5725077070730326
LEARNING_RATE:
  value: 0.3043320186526415
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
