wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.35519771540583167
LEARNING_RATE:
  value: 0.7462220228558054
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
