wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.4897623229321646
LEARNING_RATE:
  value: 0.6654722007413519
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 64
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
