wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.7053365067660351
LEARNING_RATE:
  value: 0.7141363921576693
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
