wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.5409862605275021
LEARNING_RATE:
  value: 0.5802259113027657
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 512
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
