wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.32873063869744146
LEARNING_RATE:
  value: 0.7596667979214881
NUMBER_HIDDEN_LAYERS:
  value: 1
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
