wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.1989431070311675
LEARNING_RATE:
  value: 0.34505756032768986
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
