wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.6679832748615081
LEARNING_RATE:
  value: 0.2226495338992005
NUMBER_HIDDEN_LAYERS:
  value: 1
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
