wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.26079261323943514
LEARNING_RATE:
  value: 0.6024000742319388
NUMBER_HIDDEN_LAYERS:
  value: 2
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
