wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.8549923327271424
LEARNING_RATE:
  value: 0.3317248438721432
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 512
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
