wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.9635453627881466
LEARNING_RATE:
  value: 0.26476610923796773
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
