wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.8428482234184534
LEARNING_RATE:
  value: 0.3572480178701968
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 128
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
