wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.67985587457628
LEARNING_RATE:
  value: 0.9936604818516348
NUMBER_HIDDEN_LAYERS:
  value: 1
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
