wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.5996781193144345
LEARNING_RATE:
  value: 0.16840543135597108
NUMBER_HIDDEN_LAYERS:
  value: 2
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
