wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.6745252020256214
LEARNING_RATE:
  value: 0.8353228128245221
NUMBER_HIDDEN_LAYERS:
  value: 1
SIZE_HIDDEN_LAYER:
  value: 64
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
