wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100
EPSILON:
  value: 0.33576177144079955
LEARNING_RATE:
  value: 0.5079430711198109
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 512
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
