wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.4192450460876743
LEARNING_RATE:
  value: 0.6430392786511251
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 128
UPDATE_PERIOD:
  value: 1
optimizer:
  value: sgd
