wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.31194573049515706
LEARNING_RATE:
  value: 0.3717839604227049
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 512
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
