wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.460810358328969
LEARNING_RATE:
  value: 0.7201319146538671
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
