wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.6921394505822182
LEARNING_RATE:
  value: 0.5050728241902772
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 32
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
