wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.5785648201390576
LEARNING_RATE:
  value: 0.4726953113785409
NUMBER_HIDDEN_LAYERS:
  value: 0
SIZE_HIDDEN_LAYER:
  value: 128
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
