wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.9999040205778514
LEARNING_RATE:
  value: 0.371023773399762
NUMBER_HIDDEN_LAYERS:
  value: 2
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
