wandb_version: 1

BATCH_SIZE:
  value: 32
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.3240860181969851
LEARNING_RATE:
  value: 0.7738391689197606
NUMBER_HIDDEN_LAYERS:
  value: 3
SIZE_HIDDEN_LAYER:
  value: 256
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
