wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.18874333352293185
LEARNING_RATE:
  value: 0.2634139421756301
NUMBER_HIDDEN_LAYERS:
  value: 1
SIZE_HIDDEN_LAYER:
  value: 128
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
