wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.3911723816603955
LEARNING_RATE:
  value: 0.0493071651249558
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: adam
