wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.27522906741744996
LEARNING_RATE:
  value: 0.021154844496400343
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 1
optimizer:
  value: sgd
