wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 1000
EPSILON:
  value: 0.10976597778533616
LEARNING_RATE:
  value: 0.0505019663483068
NUMBER_INNER_LAYERS:
  value: 3
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: sgd
