wandb_version: 1

BATCH_SIZE:
  value: 16
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.3971381256993236
LEARNING_RATE:
  value: 0.06141852559546663
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: sgd
