wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 100000
EPSILON:
  value: 0.2360567521668119
LEARNING_RATE:
  value: 0.03656541949412416
NUMBER_INNER_LAYERS:
  value: 1
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
