wandb_version: 1

BATCH_SIZE:
  value: 64
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.21598756248522108
LEARNING_RATE:
  value: 0.061615604990291215
NUMBER_INNER_LAYERS:
  value: 2
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 10
optimizer:
  value: adam
