wandb_version: 1

BATCH_SIZE:
  value: 128
BUFFER_SIZE:
  value: 10000
EPSILON:
  value: 0.3745297488657613
LEARNING_RATE:
  value: 0.04223163411994115
NUMBER_INNER_LAYERS:
  value: 0
SIZE_INNER_LAYER:
  value: 50
UPDATE_PERIOD:
  value: 15
optimizer:
  value: adam
